database:
    launch: "clustered"
run_args:
    nodes: 2
    db_nNodes: 1
    sim_nNodes: 1
    cores_pn: 32
    simprocs: 8
    simprocs_pn: 8
    dbprocs_pn: 32
    device: "cuda"
    cpu_bind: "none"
    network_interface: "hsn0"
experiment:
    port: 6780
    name: "inference-example"
    launcher: "pbs"
    executable: "./src/inference.py"
model:
    path: "./model_jit.pt"
    backend: "TORCH"
    device: "gpu"
    batch: 0
    devices_per_node: 1
logging: "no" 
